@KioskoManager.API_HostAddress = http://localhost:5142

###

GET {{KioskoManager.API_HostAddress}}/api/categorias
Accept: application/json

###

POST {{KioskoManager.API_HostAddress}}/api/categorias
Content-Type: application/json

{
  "nombreCategoria": "Congelados"
}

###

GET {{KioskoManager.API_HostAddress}}/api/productos
Accept: application/json

###

POST {{KioskoManager.API_HostAddress}}/api/productos
Content-Type: application/json

{
  "nombreProducto": "Coca Cola 500ml",
  "codigoBarras": "779089400001",
  "precioCompra": 1200,
  "precioVenta": 1800,
  "stockActual": 50,
  "stockMinimo": 10,
  "idCategoria": 1
}
###

GET {{KioskoManager.API_HostAddress}}/api/productos/1

###

PUT {{KioskoManager.API_HostAddress}}/api/productos/1
Content-Type: application/json

{
  "nombreProducto": "Coca Cola 600ml",
  "codigoBarras": "779089500001",
  "precioCompra": 1500,
  "precioVenta": 2500,
  "stockActual": 40,
  "stockMinimo": 10,
  "idCategoria": 1
}

###

DELETE {{KioskoManager.API_HostAddress}}/api/productos/1

  ### Usuarios

GET {{KioskoManager.API_HostAddress}}/api/usuarios

###

GET {{KioskoManager.API_HostAddress}}/api/usuarios/1

###

POST {{KioskoManager.API_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nombreUsuario": "Admin",
  "apellidoUsuario": "Sistema",
  "emailUsuario": "admin",
  "passwordHash": "admin",
  "rolUsuario": "DUENIO",
  "activoUsuario": true
}

###

PUT {{KioskoManager.API_HostAddress}}/api/usuarios/1
Content-Type: application/json

{
  "nombreUsuario": "Admin",
  "apellidoUsuario": "Modificado",
  "emailUsuario": "admin",
  "passwordHash": "admin",
  "rolUsuario": "DUENIO",
  "activoUsuario": true
}

###

DELETE {{KioskoManager.API_HostAddress}}/api/usuarios/1




### LOGIN

POST {{KioskoManager.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "admin"
}


### VENTAS  

POST {{KioskoManager.API_HostAddress}}/api/ventas
Content-Type: application/json

{
  "idUsuario": 2,
  "detalles": [
    {
      "idProducto": 1,
      "cantidad": 2
    }
  ]
}

### MOVIMIENTOS STOCK

GET {{KioskoManager.API_HostAddress}}/api/movimientosstock
Accept: application/json


### Buscar producto

GET {{KioskoManager.API_HostAddress}}/api/productos/buscar?texto=779089500001
Accept: application/json


### Productos con stock bajo

GET {{KioskoManager.API_HostAddress}}/api/productos/stock-bajo
Accept: application/json